[package]
name = "uxum"
version = "0.1.0"
authors = ["Alex Unigovsky <unik@devrandom.ru>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
axum = "0.6"
humantime-serde = "1.1"
hyper = {version = "0.14", features = ["http2", "server"]}
serde = {version = "1.0", features = ["derive"]}
thiserror = "1.0"
tokio = {version = "1.33", features = ["full"]}

[dev-dependencies]

[[example]]
name = "basic_server"
