logging:
  subscribers:
    - format: pretty
      level: TRACE
      targets:
        h2: INFO
        hyper: INFO
        tonic: INFO
        tower: INFO
      color: true
    - format: compact
      level: DEBUG
      output:
        type: file
        path: advanced_server.log
    - format: json
      level: DEBUG
      output:
        type: file
        path: advanced_server.json.log
      flatten_metadata: true
      current_span: true
      static_fields:
        env: dev
        something: something
        other: 42
handlers:
  hello_world:
    disabled: false
    rate_limit:
      rps: 1
metrics:
  labels:
    env: example
tracing:
  endpoint: http://localhost:4317
  include:
    location: true
    exception_from_error_fields: true
    exception_from_error_events: true
    status_from_error_events: true
    inactivity: true
    thread_info: true
  level: TRACE
auth:
  users:
    test:
      password: test
      roles:
        - role1
        - role2
    guest:
      password: guest
    super:
      password: super
      roles:
        - super
  roles:
    super:
      super_user: true
    role1:
      permissions:
        - perm1
        - perm2
    role2:
      permissions:
        - perm3
        - perm4
server:
  listen: 127.0.0.1:8080
